apiVersion: v2
name: anythingllm
description: A Helm Chart of AnythingLLM
type: application
appVersion: "1.1.4"
version: 0.1.0

dependencies:
  - name: anything-llm
    repository: "https://la-cc.github.io/anything-llm-helm-chart"
    version: "1.1.4"
  - name: chromadb
    repository: "https://amikos-tech.github.io/chromadb-chart/"
    version: "0.1.24"
