anything-llm:
  image: 
    repository: ghcr.io/mintplex-labs/anything-llm
    tag: 1.1.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3001

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      cert-manager.io/cluster-issuer: 
      cert-manager.io/renew-before:
    hosts: 
      - host: anythingllm.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []

  config:
    STORAGE_DIR: "/app/server/storage"
    AZURE_OPENAI_ENDOINT: "https://your-azure-openai-endpoint/"
    EMBEDDING_MODEL_PREF: "text-embedding-3-large"
    EMBEDDINGS_MODEL_MAX_CHUNK_LENGTH: 8192
    EMBEDDING_ENGINE: "azure"
    VECTOR_DB: "chroma"
    CHROMA_ENDPOINT: "http://chromadb:8000"
    
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    volumes:
      - name: server-storage
        mountPath: /app/server/storage
      
  chromadb:
    enabled: false
    chromadb:
      auth:
        enabled: false
    service:
      type: ClusterIP