postgresql:
  image:
    registry: khangvutsocial
    repository: pgvector
    tag: latest
    pullPolicy: IfNotPresent
  auth:
    enablePostgresUser: true
    postgresPassword: "your-postgres-password"
    username: "postgres"
    password: "postgres"
    database: "postgres"
    # existingSecret: "postgresql-secrets"
    # secretKeys:
    #   adminPasswordKey: postgres-password
    #   userPasswordKey: user-password
    #   replicationPasswordKey: replication-password
  architecture: standalone
  containerPorts:
    postgresql: 5432
  primary:
    name: primary
    containerSecurityContext:
      enabled: true
      seLinuxOptions: {}
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: "RuntimeDefault"
  readReplicas:
    name: read
    replicaCount: 1
