apiVersion: v2
name: chromadb
description: A Helm Chart for ChromaDB
type: application
appVersion: "0.1.24"
version: 0.1.0

dependencies:
  - name: chromadb
    repository: "https://amikos-tech.github.io/chromadb-chart/"
    version: "0.1.24"
