apiVersion: v1
name: cert-manager
description: A Helm chart for cert-manager
kubeVersion: '>= 1.22.0-0'

version: v1.13.2
appVersion: v1.13.2

dependencies:
- name: cert-manager
  repository: https://charts.jetstack.io
  version: 1.13.2